# Change these first
owner: bengalproductions # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Bengal Productions Website
    url: https://bengal.productions
  - name: Assets Server
    url: https://assets.bengal.productions
  - name: Pate Resources
    url: https://pateresources.co.uk
  - name: GymDays
    url: https://gymdays.co.uk
  - name: Where Have I Been?
    url: https://wherehaveibeen.co.uk
  - name: BengalBeats
    url: https://bengalbeats.co.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bengal.productions
  # baseUrl: /your-repo-name
  favicon: https://assets.bengal.productions/favicon.ico
  logoUrl: https://assets.bengal.productions/logos/bengalprod/bplogo.svg
  name: Bengal Productions
  introTitle: "Keep up-to-date with the current status of Bengal Productions products!"
  introMessage: This is status page is automatically updated every time we have an issue and is updated by us during every incident.
  navbar:
    - title: Status
      href: /
    - title: Back to Bengal Productions
      href: https://bengal.productions

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
